# version: "3.9"

services:
  env:
    build:
      context: .
      dockerfile: Dockerfile.env
    container_name: agent_env
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - runs:/app/runs

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 3s

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: agent_runner
    depends_on:
      - env
    environment:
      - ENV_MODE=remote
      - BASE_URL=http://env:8000/v1
      - LOG_DIR=/app/logs/runs
    volumes:
      - logs:/app/logs
      - runs:/app/runs

volumes:
  logs:
  runs: